version: '3.8'

services:
  laravel:
    build:
      context: ../
      dockerfile: docker/php.dockerfile
    container_name: laravel_app
    working_dir: /var/www/html
    volumes:
      - ./../src:/var/www/html
    depends_on:
      - db
    restart: always

  nginx:
    image: nginx:alpine
    container_name: laravel_nginx
    ports:
      - "8080:80"
    volumes:
      - ./../src:/var/www/html
      - ./../docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - laravel
    restart: always

  db:
    image: postgres:15
    container_name: laravel_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: fundamental_db
    volumes:
      - data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always

volumes:
  data:
